In [1]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt

In [2]:
pip install tensorflow==2.9.1

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 511.7 MB 7.0 kB/s 
  Attempting uninstall: tensorflow
    Found existing installation: tensorflow 2.9.2
    Uninstalling tensorflow-2.9.2:
      Successfully uninstalled tensorflow-2.9.2


In [3]:
import tensorflow_datasets as tfds

In [4]:
!pip install tensorflow-datasets

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [5]:
from google.colab import files
uploaded=files.upload()


Saving data.csv to data.csv


In [6]:
import pandas as pd
import io
df=pd.read_csv(io.BytesIO(uploaded['data.csv']),on_bad_lines='skip')
print(df)

    concentration  temp  dosage  removal
0             140   313     1.0    86.60
1             140   303     1.0    86.06
2             140   313     1.0    87.52
3             140   323     1.0    88.42
4             140   313     1.0    87.35
5             140   313     1.0    86.98
6             140   313     1.0    87.35
7             140   313     0.5    85.57
8             140   313     1.0    87.26
9             140   313     1.5    87.64
10             80   313     1.0    92.73
11             80   313     1.0    91.98
12             80   303     1.0    92.19
13             80   313     1.5    93.76
14             80   313     1.0    91.58
15             80   313     1.0    92.64
16             80   323     1.0    93.26
17             80   313     1.0    92.73
18             80   313     1.0    92.57
19             80   313     0.5    91.69
20            380   313     1.0    62.11
21            380   313     0.5    61.08
22            380   313     1.0    61.11
23            38

In [7]:
!pip install datasets

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 441 kB 28.1 MB/s 
     |████████████████████████████████| 163 kB 73.4 MB/s 
     |████████████████████████████████| 115 kB 78.4 MB/s 
     |████████████████████████████████| 212 kB 73.7 MB/s 
     |████████████████████████████████| 127 kB 33.8 MB/s 
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.24.3
    Uninstalling urllib3-1.24.3:
      Successfully uninstalled urllib3-1.24.3


In [8]:
from datasets import load_dataset

In [9]:
loaded_data=load_dataset('csv',data_files='data.csv',on_bad_lines='skip')

Extracting data files:   0%|          | 0/1 [00:00<?, ?it/s]

0 tables [00:00, ? tables/s]

Dataset csv downloaded and prepared to /root/.cache/huggingface/datasets/csv/default-6807ff7b8cdd8547/0.0.0/6b34fb8fcf56f7c8ba51dc895bfa2bfbe43546f190a60fcf74bb5e8afdcc2317. Subsequent calls will reuse this data.


  0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
#(train_concentartion,train_temp,train_dosage,train_removal),(test_concentartion,test_temp,test_dosage,test_removal)=loaded_data

ValueError: ignored

In [61]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor

In [10]:
train=pd.read_csv('data.csv',on_bad_lines='skip')

In [11]:
test=pd.read_csv('data.csv',on_bad_lines='skip')

In [12]:
train.shape

(46, 4)

In [13]:
type(train)

pandas.core.frame.DataFrame

In [14]:
print(train)

    concentration  temp  dosage  removal
0             140   313     1.0    86.60
1             140   303     1.0    86.06
2             140   313     1.0    87.52
3             140   323     1.0    88.42
4             140   313     1.0    87.35
5             140   313     1.0    86.98
6             140   313     1.0    87.35
7             140   313     0.5    85.57
8             140   313     1.0    87.26
9             140   313     1.5    87.64
10             80   313     1.0    92.73
11             80   313     1.0    91.98
12             80   303     1.0    92.19
13             80   313     1.5    93.76
14             80   313     1.0    91.58
15             80   313     1.0    92.64
16             80   323     1.0    93.26
17             80   313     1.0    92.73
18             80   313     1.0    92.57
19             80   313     0.5    91.69
20            380   313     1.0    62.11
21            380   313     0.5    61.08
22            380   313     1.0    61.11
23            38

In [15]:
df.dtypes

concentration      int64
temp               int64
dosage           float64
removal          float64
dtype: object

In [16]:
class_names=['concentration','temp','dosage']
num_feature=df[class_names]
num_feature.head()



concentration  temp  dosage
0            140   313     1.0
1            140   303     1.0
2            140   313     1.0
3            140   323     1.0
4            140   313     1.0

In [54]:
num_feature.shape

(46, 3)

In [17]:
tf.convert_to_tensor(num_feature)

<tf.Tensor: shape=(46, 3), dtype=float64, numpy=
array([[140. , 313. ,   1. ],
       [140. , 303. ,   1. ],
       [140. , 313. ,   1. ],
       [140. , 323. ,   1. ],
       [140. , 313. ,   1. ],
       [140. , 313. ,   1. ],
       [140. , 313. ,   1. ],
       [140. , 313. ,   0.5],
       [140. , 313. ,   1. ],
       [140. , 313. ,   1.5],
       [ 80. , 313. ,   1. ],
       [ 80. , 313. ,   1. ],
       [ 80. , 303. ,   1. ],
       [ 80. , 313. ,   1.5],
       [ 80. , 313. ,   1. ],
       [ 80. , 313. ,   1. ],
       [ 80. , 323. ,   1. ],
       [ 80. , 313. ,   1. ],
       [ 80. , 313. ,   1. ],
       [ 80. , 313. ,   0.5],
       [380. , 313. ,   1. ],
       [380. , 313. ,   0.5],
       [380. , 313. ,   1. ],
       [380. , 313. ,   1. ],
       [380. , 313. ,   1.5],
       [380. , 313. ,   1. ],
       [380. , 313. ,   1. ],
       [380. , 303. ,   1. ],
       [380. , 323. ,   1. ],
       [380. , 313. ,   1. ],
       [320. , 313. ,   1. ],
       [320. , 313. ,

In [18]:
result=['removal']

In [51]:
label=df[result]

In [52]:
tf.convert_to_tensor(label)

<tf.Tensor: shape=(46, 1), dtype=float64, numpy=
array([[86.6 ],
       [86.06],
       [87.52],
       [88.42],
       [87.35],
       [86.98],
       [87.35],
       [85.57],
       [87.26],
       [87.64],
       [92.73],
       [91.98],
       [92.19],
       [93.76],
       [91.58],
       [92.64],
       [93.26],
       [92.73],
       [92.57],
       [91.69],
       [62.11],
       [61.08],
       [61.11],
       [62.12],
       [63.15],
       [61.38],
       [61.95],
       [61.58],
       [62.18],
       [62.11],
       [68.24],
       [68.58],
       [67.46],
       [68.24],
       [67.21],
       [67.49],
       [69.27],
       [68.77],
       [67.71],
       [68.54],
       [48.84],
       [74.87],
       [74.61],
       [51.04],
       [70.96],
       [72.37]])>

In [53]:
label.head()

removal
0    86.60
1    86.06
2    87.52
3    88.42
4    87.35

In [55]:
label.shape


(46, 1)

In [65]:
X = df.loc[:, class_names]
y = df.loc[:, ['removal']]

In [66]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0, train_size = .75)

In [67]:
X_train.shape

(34, 3)

In [108]:
X_train.head()

concentration  temp  dosage
42            260   313     1.0
2             140   313     1.0
45            260   313     1.0
18             80   313     1.0
15             80   313     1.0

In [69]:
X_test.shape

(12, 3)

In [70]:
y_train.shape

(34, 1)

In [71]:
y_test.shape

(12, 1)

In [87]:
y_test.head()

removal
25    61.38
22    61.11
28    62.18
4     87.35
10    92.73

In [72]:
from sklearn.tree import DecisionTreeRegressor

In [73]:
reg = DecisionTreeRegressor(max_depth = 2, random_state = 0)

In [74]:
reg.fit(X_train, y_train)

DecisionTreeRegressor(max_depth=2, random_state=0)

In [93]:
y_pred=reg.predict(X_test[0:10])
print(y_pred)

[62.035 62.035 62.035 87.142 92.38  68.09  62.035 92.38  62.035 68.09 ]


In [76]:
X_test.head(1)

concentration  temp  dosage
25            380   313     1.0

In [94]:
y_pred=reg.predict(X_test.iloc[4].values.reshape(1,-1))
print(y_pred)

[92.38]


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  "X does not have valid feature names, but"


In [86]:
score = reg.score(X_test, y_test)
print(score)

0.9985105795533135


In [79]:
max_depth_range = list(range(1, 25))
# List to store the average RMSE for each value of max_depth:
r2_list = []
for depth in max_depth_range:
    reg = DecisionTreeRegressor(max_depth = depth,
                            random_state = 0)
    reg.fit(X_train, y_train)   
    
    score = reg.score(X_test, y_test)
    r2_list.append(score)

In [107]:
import matplotlib.pyplot as plt
plt.style.use('seaborn-whitegrid')

In [106]:
plt.figure()

plt.show()
#plot graph

<Figure size 432x288 with 0 Axes>

In [110]:
features = np.array([[500, 303, 0.5]])
prediction = reg.predict(features)
print("Prediction: {}".format(prediction))

Prediction: [48.84]


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  "X does not have valid feature names, but"
